/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "var(--color-on-background)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary-container": "var(--color-tertiary-container)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-primary": "var(--color-on-primary)",
        "inverse-surface": "var(--color-inverse-surface)",
        "primary-container": "var(--color-primary-container)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-error": "var(--color-on-error)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "background": "var(--color-background)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "secondary": "var(--color-secondary)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-dim": "var(--color-surface-dim)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface-tint": "var(--color-surface-tint)",
        "surface-variant": "var(--color-surface-variant)",
        "tertiary": "var(--color-tertiary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-secondary": "var(--color-on-secondary)",
        "outline-variant": "var(--color-outline-variant)",
        "primary": "var(--color-primary)",
        "surface": "var(--color-surface)",
        "on-error-container": "var(--color-on-error-container)",
        "outline": "var(--color-outline)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-container": "var(--color-surface-container)",
        "on-surface": "var(--color-on-surface)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "error-container": "var(--color-error-container)",
        "error": "var(--color-error)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-highest": "var(--color-surface-container-highest)",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["Roboto Mono", "monospace"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "2xl": "1rem", "full": "9999px"},
    },
  },
  plugins: [],
}
